version: "2"

networks:
  app-tier:
    driver: bridge

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - app-tier
    hostname: zookeeper-server

  kafka:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - app-tier
    hostname: kafka-server

  kafka-producer:
    image: quay.io/weteh/kafka-producer-app:0.1
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-server:9092
      - KAFKA_TOPIC=testTopic
      - KAFKA_CLIENT_ID=test1
    networks:
      - app-tier

  kafka-consumer:
    image: quay.io/weteh/kafka-consumer-app:0.1
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka-server:9092
      - KAFKA_TOPIC=testTopic
      - KAFKA_CLIENT_ID=test2
      - KAFKA_GROUP_ID=testGroup
    networks:
      - app-tier

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
